# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

title                    : "Lomvardas Lab"
title_subtitle           : "Aphrodite Server"
# title_separator          : "-"
# description              : "."
# favicon                  : "/assets/img/aphrodite_bust.svg"
# avatar                   : "/assets/img/aphrodite_bust.svg"
# url                      : "https://localhost:4000" # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"

# Site Author
author:
  name                   : "David Ankin"

collections:
  people:
    output: true
    permalink: /:collection/:title/

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-less

exclude:
  - '**/README.md'
  - Gemfile
  - Gemfile.lock
  - .gitignore
  - bower_components
  - custom_bower_components
  - bower.json
  - node_modules
  - package.json

include:
  - bower_components/bootstrap
